### ISSUE TITLE
can you teach me how to use this please I don't know anything about py. file.

### ISSUE THREAD

**Issue by frpp22** [vscala/Spellcast-Word-Finder#4]

**Comment by HelpUwithCoding** [comment]
its not that hard at all i figured it outby myself

**Comment by ghost** [comment]
dm me on discord @knownasnosh and i can send you the exe

**Comment by vscala** [comment]
Hello, I used ChatGPT to generate this guide that might help you.

1. Install Python: Download and install Python on your computer from the official Python website (https://www.python.org/downloads/).
2. Run the Program: Open a terminal or command prompt, navigate to the folder where you saved gui.py, and run the following command:

``` 
python gui.py 
```

3. This will execute your tkinter Python program, and the GUI window will appear on your screen.
