### ISSUE TITLE
how to use it😭😭😭😭😭

### ISSUE THREAD

**Issue by ZiomkowyAlek** [vscala/Spellcast-Word-Finder#7]

**Comment by vscala** [comment]
Hello, I used ChatGPT to generate this guide that might help you.

1. Install Python: Download and install Python on your computer from the official Python website (https://www.python.org/downloads/).
2. Run the Program: Open a terminal or command prompt, navigate to the folder where you saved gui.py, and run the following command:

``` 
python gui.py 
```

3. This will execute your tkinter Python program, and the GUI window will appear on your screen.

**Comment by miqumi** [comment]
💀👍

**Comment by miqumi** [comment]
alt title: im blind
https://github.com/vscala/Spellcast-Word-Finder#get-started
